name: test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: snok/install-poetry@v1.1.1
        with:
          virtualenvs-create: false
          virtualenvs-in-project: false
      - name: Install Dependencies
        run: |
          poetry install
      - name: Run Lint
        run: |
          make lint
      - name: Run Tests
        run: |
          make test
